name: 'Build & Deployment'

# Controls when the workflow will run
on:
    # Triggers the workflow on push events but only for the "main" branch
    push:
      branches: [ "main", "feature/*" ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
env:
    testInheritVariable: the test variable
    NUGET_ENDPOINT: 'https://pkgs.dev.azure.com/daimler/FbDriverGrading/_packaging/FbDriverGradingNuGet/nuget/v3/index.json'
    NUGET_FEED_NAME: 'AZURE_DEVOPS'

jobs: 
    
    job_docker_build:
      runs-on: windows-latest
      steps:
         - name: 'Docker Build'
           run: dotnet nuget add source ${{ env.NUGET_ENDPOINT }} --name ${{ env.NUGET_FEED_NAME }} --username az --password 7aqdjtbscxnufd472ejhcq3pyvoni6ydnv7vjqldf7eebotwltuq
